#!/bin/sh

### BEGIN INIT INFO
# Provides:        space_switch
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Start Nova Labs space switch
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

SCRIPT_DIR=/root/space_switch
DAEMON=${SCRIPT_DIR}/main.py
PIDFILE=/var/run/space_switch.pid

test -x $DAEMON || exit 5

RUNASUSER=root

cd $SCRIPT_DIR

case $1 in
        start)
                log_daemon_msg "Starting space_switch" "main.py"
#               start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON -- -p $PIDFILE
                $DAEMON &
                status=$?
                pid=$!
                echo $pid > $PIDFILE
                log_end_msg $status
                ;;
        stop)
                log_daemon_msg "Stopping space_switch" "main.py"
                start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
                log_end_msg $?
                rm -f $PIDFILE
                ;;
        restart|force-reload)
                $0 stop && sleep 2 && $0 start
                ;;
        try-restart)
                if $0 status >/dev/null; then
                        $0 restart
                else
                        exit 0
                fi
                ;;
        reload)
                exit 3
                ;;
        status)
                status_of_proc $DAEMON "space_switch"
                ;;
        *)
                echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
                exit 2
                ;;
esac
